sudo: required
language: generic
services:
  - docker
script:
  - docker build -t kzeenpizza -f ops/Dockerfile .
notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always
