language: ruby
cache: bundler
bundler_args: --deployment --local -j 4
script:
  - export PATH=$PATH:/usr/lib/chromium-browser/
  - bundle exec rake db:setup
  - bundle exec rspec
  - bundle exec rake assets:precompile
notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always
addons:
  apt:
    packages:
      # - chromium-driver  # newer releases
      - chromium-chromedriver
