sudo: required
language: ruby
cache: bundler
bundler_args: --deployment --local -j 4
addons:
-  chrome: stable
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - bundle exec rake db:setup
  - bundle exec rspec
  - bundle exec rake assets:precompile
notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always
