language: ruby
cache: bundler
bundler_args: --deployment --local -j 4
script:
  - bundle exec rake db:setup
  - bundle exec rake assets:precompile
  - bundle exec rspec
notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always
