language: ruby
cache: bundler
bundler_args: --deployment --local -j 4
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - bundle exec rake db:setup
  - bundle exec rspec
  - bundle exec rake assets:precompile
addons:
  chrome: stable
