# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 636f4a4efce0c7550323938faf7918c793a03381266fd6de595b1975cd05b0619a505057bc93df450d36067404676307cf269fee62db74d7f5a1c13ddef45aca

test:
  secret_key_base: 01d20544739dc46a06370f00cf6163003307ff9ffb3454cff5c9ee31057c6b2ad95710b649b0a567ff7eb9bdc4a5062489397e6b760c47eef47320ba00f4e804

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  # XXX: we have no secrets, so hardcode this until we do.
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 7f47bc96e04a37b939c492b3615fb5343b96d4d648aff877b7270eacbdc87f4a65ab9b546fa251df2c22d02faa6d6b9b85710c3c88d2c486de879fd9b05e64fa
